collections:
  tips: '/tip/{slug}'
  rips: '/rip/{slug}'
  blog: '/blog/{slug}'
taxonomies:
  label: '/label/{slug}'
  price: '/price/{slug}'
  tag: '/tag/{slug}'
  genre: '/genre/{slug}'
  style: '/style/{slug}'
  region: '/region/{slug}'
  star: '/starred/{slug}'
routes:
  /search:
    template: search
    title: 'Search Results'
